# Generated by Django 3.0.5 on 2020-12-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0004_auto_20201225_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(default='main/static/img/project.png', upload_to='media/img'),
        ),
    ]
