# Generated by Django 3.0.5 on 2020-12-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0008_auto_20201225_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
