# Generated by Django 3.0.5 on 2020-12-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0009_auto_20201225_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project',
            field=models.FileField(default='myDiplom/default.txt', upload_to='Ue4Project'),
        ),
    ]
