# Generated by Django 3.0.5 on 2020-12-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0010_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project',
        ),
    ]
