# Generated by Django 3.0.5 on 2020-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0012_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.FileField(default='default.txt', upload_to=''),
        ),
    ]
