# Generated by Django 3.0.5 on 2020-12-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0013_auto_20201225_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.FileField(default='default.txt', upload_to='Ue4Project/'),
        ),
    ]
