# Generated by Django 3.0.5 on 2020-12-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0014_auto_20201226_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.FileField(default='default.txt', upload_to=''),
        ),
    ]
