# Generated by Django 3.0.5 on 2020-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0015_auto_20201226_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='headline_name',
            field=models.CharField(default='name1', max_length=30),
        ),
    ]
