# Generated by Django 3.0.5 on 2021-02-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0018_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('project_id', models.CharField(max_length=20)),
                ('like', models.CharField(max_length=1)),
            ],
        ),
    ]
