# Generated by Django 3.0.5 on 2021-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0023_chat_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('project_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='img2',
            field=models.ImageField(default='img.img', upload_to='img'),
        ),
        migrations.AddField(
            model_name='projects',
            name='img3',
            field=models.ImageField(default='img.img', upload_to='img'),
        ),
    ]
