# Generated by Django 3.0.5 on 2021-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0024_auto_20210227_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
    ]
